In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [2]:
df=pd.read_csv('data/stud.csv')

In [3]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
X=df.drop(columns=['math_score'],axis=1)

In [5]:
X.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [6]:
y=df['math_score']
print(y)

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

#StandardScaler

In [7]:
num_feature=X.select_dtypes(exclude="object").columns
cate_feature=X.select_dtypes(include="object").columns

from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

num_transformer=StandardScaler()
cate_transformer=OneHotEncoder()


perprocessor=ColumnTransformer(
    [
        ("StandardScaler",num_transformer,num_feature),
        ("OneHotEncoder",cate_transformer,cate_feature)
    ]
)

In [8]:
X=perprocessor.fit_transform(X)

In [9]:
X.shape

(1000, 19)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 19), (200, 19), (800,), (200,))

In [11]:

from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso

In [12]:
models=[LinearRegression(),Ridge(),Lasso(),DecisionTreeRegressor(),RandomForestRegressor(),AdaBoostRegressor()]

In [14]:
for model in models:
    model.fit(X_train,y_train)
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    
    from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
    mse=mean_squared_error(y_train,y_train_pred)
    mae=mean_absolute_error(y_train,y_train_pred) 
    r2_square_train = r2_score(y_train,y_train_pred)
    print(f"{model} \n Mean Squared Error for train data: {mse} \n Mean Absolute Error for train data: {mae} \n R2 Score for train data: {r2_square_train}")
    
    print("----------------------------------------------------------------------")
    
    mse=mean_squared_error(y_test,y_test_pred)
    mae=mean_absolute_error(y_test,y_test_pred)
    r2_square = r2_score(y_test,y_test_pred)
    print(f" \n Mean Squared Error for test data: {mse} \n Mean Absolute Error for test data: {mae} \n R2 Score for test data: {r2_square}")
    
    print("################################################################################")
    print("\n")

LinearRegression()
 Mean Squared Error for train data: 28.354688720703123
 Mean Absolute Error for train data: 4.2696484375
 R2 Score for train data: 0.8742292973337312
----------------------------------------------------------------------

 Mean Squared Error for test data: 29.1463720703125
 Mean Absolute Error for test data: 4.21859375
 R2 Score for test data: 0.8802228827414312
################################################################################


Ridge()
 Mean Squared Error for train data: 28.33778823308244
 Mean Absolute Error for train data: 4.26498782372598
 R2 Score for train data: 0.8743042615212909
----------------------------------------------------------------------

 Mean Squared Error for test data: 29.056272192348302
 Mean Absolute Error for test data: 4.211100688014261
 R2 Score for test data: 0.8805931485028737
################################################################################


Lasso()
 Mean Squared Error for train data: 43.478297882726196
 Mean Absolute Error for train data: 5.206296077972952
 R2 Score for train data: 0.8071466723085148
----------------------------------------------------------------------

 Mean Squared Error for test data: 42.50633235127345
 Mean Absolute Error for test data: 5.157879138921817
 R2 Score for test data: 0.825320079562973
################################################################################


DecisionTreeRegressor()
 Mean Squared Error for train data: 0.078125
 Mean Absolute Error for train data: 0.01875
 R2 Score for train data: 0.9996534669718089
----------------------------------------------------------------------

 Mean Squared Error for test data: 63.465
 Mean Absolute Error for test data: 6.195
 R2 Score for test data: 0.739190362063694
################################################################################


RandomForestRegressor()
 Mean Squared Error for train data: 5.328146917534723
 Mean Absolute Error for train data: 1.8336322916666665
 R2 Score for train data: 0.9763663502594487
----------------------------------------------------------------------

 Mean Squared Error for test data: 36.95442801388889
 Mean Absolute Error for test data: 4.647358333333333
 R2 Score for test data: 0.8481356497211747
################################################################################


AdaBoostRegressor()
 Mean Squared Error for train data: 33.041766604705934
 Mean Absolute Error for train data: 4.691104804907437
 R2 Score for train data: 0.853439187989588
----------------------------------------------------------------------

 Mean Squared Error for test data: 35.27184584520114
 Mean Absolute Error for test data: 4.658183020273771
 R2 Score for test data: 0.8550502269875977
################################################################################

In [ ]:
regression=DecisionTreeRegressor()
regression.fit(X_train,y_train)
y_test_pred=regression.predict(X_test)
pred_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_test_pred,'Difference':y_test-y_test_pred})
print(pred_df)
print(regression)

     Actual Value  Predicted Value  Difference
521            91             85.0         6.0
737            53             42.0        11.0
740            80             75.0         5.0
660            74             69.0         5.0
411            84             76.0         8.0
..            ...              ...         ...
408            52             35.0        17.0
332            62             70.0        -8.0
208            74             72.0         2.0
613            65             66.0        -1.0
78             61             66.0        -5.0

[200 rows x 3 columns]
DecisionTreeRegressor()